export const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Orissa',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];
export const DATA = [
  {name: 'Surya', id: '1', designation: 'Accredited Estate Planner'},
  {
    name: 'Krishna',
    id: '2',
    designation: 'Certified Wealth Smart Strategist',
  },
  {name: 'Rajveer', id: '3', designation: 'Registered Fiduciary'},
];

export const URL = 'http://localhost:3000';
